export const FETCH_ERROR = 'FETCH_ERROR'
export const FETCH_LOADING = 'FETCH_LOADING'
export const FETCH_ERROR_CLEAR = 'FETCH_ERROR_CLEAR'

export const GET_PRICING_PLAN_LOADING = 'GET_PRICING_PLAN_LOADING'
export const GET_PRICING_PLAN_SUCCESS = 'GET_PRICING_PLAN_SUCCESS'
export const GET_PRICING_PLAN_ERROR = 'GET_PRICING_PLAN_ERROR'

export const ADD_PROPOSAL_LOADING = 'ADD_PROPOSAL_LOADING'
export const ADD_PROPOSAL_SUCCESS = 'ADD_PROPOSAL_SUCCESS'
export const ADD_PROPOSAL_ERROR = 'ADD_PROPOSAL_ERROR'

export const SET_SECTION = 'SET_SECTION'
export const SET_TARIFF = 'SET_TARIFF'

export const SET_HOME_PROPOSAL = 'SET_HOME_PROPOSAL'
export const SET_OFFICE_PROPOSAL = 'SET_OFFICE_PROPOSAL'

export const SET_VIEW_DEVICE = 'SET_VIEW_DEVICE'
export const SET_VIEW_MOBILE = 'SET_VIEW_MOBILE'
export const SHOW_PROPOSAL = 'SHOW_PROPOSAL'
export const HIDE_PROPOSAL = 'HIDE_PROPOSAL'
